os:
  - linux

language: c
sudo: false 
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

branches:
  only:
  - fragment

install:
  - source devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true
  - export CC=gcc
  - export CXX=g++
  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then openssl aes-256-cbc -K $encrypted_1d5273f07e71_key -iv $encrypted_1d5273f07e71_iv -in oe_license.txt.enc -out oe_license.txt -d; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" == false ]; then echo "OpenEye license will not be installed in forks."; fi

script:
  - conda config --add channels ${ORGNAME} --add channels conda-forge
  - conda install --yes --quiet pip
  - conda update --yes conda
  - pip install $OPENEYE_CHANNEL openeye-toolkits && python -c "import openeye; print(openeye.__version__)"
  - conda build devtools/conda-recipe

env:
  matrix:
    - python=3.5  CONDA_PY=35
    - python=3.6  CONDA_PY=36

  global:
    - PACKAGENAME="torsionfit"
    - ORGNAME="omnia"
    # encrypted BINSTAR_TOKEN for push of dev package to binstar
    - secure: "XeYowlJPu0iBHK81hfurJhDV+sw1WRHYxpv5Bqx8FI9kSk7PBN/IVBq0xM394qslV35r/kuSxvBl07PemdOhF/Zn/1I2es0ySYvuPsHQyUqbq406KPl/fIUXeKVqWcqkd9iJKQqaVY91okfsY8HcLO+rJ3zv3W+2ZHZWfq8qCFo="
    - OPENEYE_CHANNEL="-i https://pypi.anaconda.org/OpenEye/simple/"


after_success:
  - echo "after_success"
  - source devtools/travis-ci/after_success.sh
