os:
  - linux
  - osx

language: c
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

before_install:
  - if [["$TRAVIS_OS_NAME" == "linux"]]; then sudo apt-get install libopenblas-base
  - export LD_LIBRARY_PATH=/usr/lib/openblas-base/

install:
  - source devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true

install:
  - source devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true
  - export CC=gcc
  - export CXX=g++
  - export LD_LIBRARY_PATH=/usr/lib/openblas-base/

script:
  - conda config --add channels ${ORGNAME}
  - conda build devtools/conda-recipe
  - source activate _test
  - conda install --yes --quiet nose nose-timer
  - cd devtools && nosetests $PACKAGENAME --nocapture --verbosity=2 --with-doctest --with-timer && cd ..

env:
  matrix:
    - python=2.7  CONDA_PY=27
    - python=3.4  CONDA_PY=34
    - python=3.5  CONDA_PY=35

  global:
    - PACKAGENAME="torsionfit"
    - ORGNAME="omnia"
    # encrypted BINSTAR_TOKEN for push of dev package to binstar
    - secure: "XeYowlJPu0iBHK81hfurJhDV+sw1WRHYxpv5Bqx8FI9kSk7PBN/IVBq0xM394qslV35r/kuSxvBl07PemdOhF/Zn/1I2es0ySYvuPsHQyUqbq406KPl/fIUXeKVqWcqkd9iJKQqaVY91okfsY8HcLO+rJ3zv3W+2ZHZWfq8qCFo="

after_success:
  - echo "after_success"
  - source devtools/travis-ci/after_success.sh
