language: c
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

install:
  - source devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true

install:
  - source devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true
  - export CC=gcc
  - export CXX=g++

script:
  - conda config --add channels ${ORGNAME}
  - conda build devtools/conda-recipe
  - source activate _test
  - conda install --yes --quiet nose nose-timer
  - cd devtools && nosetests $PACKAGENAME --nocapture --verbosity=2 --with-doctest --with-timer && cd ..

env:
  matrix:
    - python=2.7  CONDA_PY=27
    - python=3.4  CONDA_PY=34
    - python=3.5  CONDA_PY=35

  global:
    - PACKAGENAME="torsionfit"
    - ORGNAME="omnia"
    # encrypted BINSTAR_TOKEN for push of dev package to binstar

after_success:
  - echo "after_success"
  - source devtools/travis-ci/after_success.sh
