language: c
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

install:
  - source devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true

script:
  - conda config --add channels https://conda.binstar.org/omnia
  - conda build devtools/conda-recipe

env:
  matrix:
    - python=2.7  CONDA_PY=27  CONDA_NPY=16
    - python=3.3  CONDA_PY=33  CONDA_NPY=17
    - python=3.4  CONDA_PY=34  CONDA_NPY=18
    - python=3.4  CONDA_PY=34  CONDA_NPY=19

  global:
    # encrypted BINSTAR_TOKEN for push of dev package to binstar

after_success:
  - echo "after_success"
  - source devtools/travis-ci/after_success.sh
