package:
  name: torsionfit-dev
  version: 0.0.0

source:
  path: ../../

requirements:
  build:
    - python
    - setuptools
    - numpy ==1.10
    - pymc
    - cclib
    - openmm-dev
    - parmed-dev
    - pandas
    - mdtraj
    - netcdf4
    - matplotlib
    - pymbar

  run:
    - python
    - numpy ==1.10
    - pymc
    - cclib
    - openmm-dev
    - parmed-dev
    - pandas
    - mdtraj
    - netcdf4
    - matplotlib
    - pymbar
    - libgfortran ==1.0.0 [linux]

test:
  requires:
    - nose
    - nose-timer
  imports:
    - torsionfit
  commands:
    - nosetests -vv --nocapture --with-timer torsionfit

about:
  home: http://github.com/choderalab/torsionfit
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A toolkit for Bayesian torsion parameterization for molecular mechanics forcefields.
