package:
  name: torsionfit-dev
  version: !!str 0.1.0.dev0

source:
  path: ../../

requirements:
  build:
    - python
    - pymc ==2.3.4 
    - cclib
    - pandas
    - openmm >=6.3
    - parmed
    - setuptools
    - mdtraj
    - netcdf4

  run:
    - python
    - pymc ==2.3.4
    - cclib
    - openmm >=6.3
    - parmed
    - pandas
    - mdtraj
    - netcdf4

test:
  requires:
    - nose
  imports:
    - torsionfit
  commands:
    - nosetests torsionfit -v

about:
  home: http://github.com/choderalab/torsionfit
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A toolkit for Bayesian torsion parameterization for molecular mechanics forcefields.
